port: 8000
tensor_parallel_size: 1
gpu_memory_utilization: 0.35
max_model_len: 4096
enable_auto_tool_choice: true
tool_call_parser: qwen3_coder
served-model-name: qwen
# vllm serve ~/models/Qwen3.5-4B-AWQ-4bit --config config_qwen_4b.yaml
